# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: 'MAIC - Wicresoft - Azure - 08 (70c31633-64b5-40a0-b859-e673c6f1f275)'
    WebAppName: ErZhaoJava
    packageForLinux: 'booty-duke-app-service'
